### PR TITLE
Make number of channels configurable

### PR DESCRIPTION
**Pull request by agrueneberg**
Mono is enough for my purpose, so I made the number of channels configurable (#30).

### CODE REVIEW

**Comment by agrueneberg** [comment]
@mattdiamond Any chance you could merge this? It's backward compatible.

**Comment by agrueneberg** [comment]
Thanks!

**Comment by robertpatrik85** [comment]
I need to use mono channel for recording audio input. I used the code from @agrueneberg . What should i put in numChannels value? I am very new to git. So no idea how to use? The default records in Stereo format.

**Comment by agrueneberg** [comment]
@robertpatrik85 Mono is just one channel, therefore `numChannels: 1` (the default is 2, stereo).

**Pull request merged**
