### PR TITLE
Major Refactoring

### PR DESCRIPTION
**Pull request by chris-rudmin**
I did a major refactored the code as I was going through it.
Also added support for recording 1 or more channels.

My changes are not backwards compatible with the existing version as I have renamed and moved and removed many things

### CODE REVIEW

**Comment by chris-rudmin** [comment]
I added support for recording using opus. This should be useful for reducing memory overhead in the worker thread and for people who want to send their audio to a server using less bandwidth.

**Comment by thnkloud9** [comment]
:+1:

**Comment by Rillke** [comment]
Can you make the sample page working again and perhaps offer some Opus export options on it? At least when [accessing it with rawgit](https://rawgit.com/chris-rudmin/Recorderjs/master/example_simple_exportwav.html), it doesn't appear to work (the log remains empty, no errors in JS error console), while the [original](https://rawgit.com/mattdiamond/Recorderjs/master/example_simple_exportwav.html) works with Chrome.

Would it be possible to enable `issues` on your repo? I think you've done a lot of work and I don't know whether it would be in scope of what Matt has in mind with this one.

**Comment by chris-rudmin** [comment]
Updated example page and enabled issues in my repo.

**Comment by chris-rudmin** [comment]
I made those changes you asked for. My changes are pretty divergent from
the original, so I understand that it might not make sense to merge this.

**Comment by Rillke** [comment]
Awesome, thank you, mentioned this at SO and my blog.

**Comment by chris-rudmin** [comment]
Closing. Too different to merge.

**Pull request closed without merging**
